package Shashank;

public class Exception_4565 
{


	public static void main(String[] args) 
	{
		int [] arr= {2,5,3,6,9,4};
		try
		{
			System.out.println(arr[800]);
		
		}
		catch (Exception e)
		{
			System.out.println("Handled");
		}
		
	}
}
